language: java
jdk:
  - oraclejdk8
  - oraclejdk9

sudo: false
dist: trusty

script:
  - mvn install

after_success:
  - mvn clean cobertura:cobertura coveralls:report

cache:
  directories:
  - $HOME/.m2
