version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
build_script:
  - mvn clean package --batch-mode -DskipTests
test_script:
  - mvn clean install --batch-mode
cache:
  - C:\Users\appveyor\.m2
